name: sme_tax
description: "SME-TAX: A Mobile-First eTIMS Compliance Platform for Kenyan SMEs"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  http: ^1.2.3
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.2
  intl: ^0.20.0
  intl_utils: ^10.0.0
  uuid: ^4.5.1
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.13
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.13.4
  file_picker: ^8.0.0
  flutter_svg: ^2.2.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
